images_seeds_path = Pathname('db/seeds/images_seeds')
user_zero = User.create! fullname: 'Armand Fardeau',
                         avatar: File.new(Rails.root.join(images_seeds_path, 'armand_fardeau.jpg')),
                         email: 'fardeauarmand@gmail.com',
                         phone_number: '0147498143',
                         password: 'adminadmin',
                         password_confirmation: 'adminadmin'

office_zero = Office.create! office_type: 'Breakfast',
                           privacy_type: 'apartment',
                           capacity: 4,
                           boards_number: 1,
                           meeting_room: 1,
                           listing_name: 'Lovely flat',
                           summary: 'A lovely place in the suburb',
                           address: '6 villa des nympheas 75020 Paris',
                           is_wifi: true,
                           is_tv: false,
                           is_locker: true,
                           is_pet_friendly: true,
                           is_coffee: true,
                           is_heating: true,
                           is_air: false,
                           is_kitchen: true,
                           price: 120,
                           active: true,
                           user_id: user_zero.id
office_zero.photos.create(image: File.new(Rails.root.join(images_seeds_path, 'apartment1.jpg')))

user_one = User.create! fullname: 'Paul Petit',
                        avatar: File.new(Rails.root.join(images_seeds_path, 'armand_fardeau.jpg')),
                        email: 'test@test.com',
                        phone_number: '0147498142',
                        password: 'adminadmin',
                        password_confirmation: 'adminadmin'

office_zero = Office.create! office_type: 'Breakfast',
                           privacy_type: 'apartment',
                           capacity: 4,
                           boards_number: 1,
                           meeting_room: 1,
                           listing_name: 'A nice place',
                           summary: 'A nice place in the center of Paris',
                           address: '26 rue de rivoli 75001 Paris',
                           is_wifi: true,
                           is_tv: false,
                           is_locker: true,
                           is_pet_friendly: true,
                           is_coffee: true,
                           is_heating: true,
                           is_air: false,
                           is_kitchen: true,
                           price: 120,
                           active: true,
                           user_id: user_one.id
office_zero.photos.create(image: File.new(Rails.root.join(images_seeds_path, 'apartment1.jpg')))
