language: ruby
cache: bundler
rvm:
- 2.4.1
sudo: false
before_script:
- bundle exec rake db:migrate
- bundle exec rails s -d
script:
- bundle exec rake test
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: fDqURUWFNIY0CuDzHLOF5UoSyi5TMJY+FjWF+xRI9199dVCXnN0Og3WQ5CVmzgkdpDFrCIZm8tr1P4uIocNM3pw6RlunQjrnH7qdjz9NwvvtuWwEpktpsevhg+7V/uWM4bNjzlz+GPsvbW7qxlN0B1uogpQfkKhHnMfmKuwHy9e1mWgKYxMq7T1+uqFFEUZg2Hmi9uwHE/sZCkDzOCMkvJi/yGi0mbUW3c8Gob5nX8cZjh6PzbCrLPoqCqDj4xmzMbOjbzY0GJ80aKsCvb4auBYWU4y2uYrx8sDYjEZnzxWMYqhqghidbl4zpP3NzOCcxZtRxYjzrm3A7oR8tI39m2jy6D92WGyWN7OnQ7TjmE1AMe8mx8HRI5dVijcczkcxEa6gyDRbalmbi8gdTnpW5Pctp5W28goxl+e5qCP1MkZXGMxWfcLS2q5XBiyVuoYe0QxXwY8ZH5A+VWZmpl6dmYyi9dxh6oXT65UhACY2GK1GZlA8RGgyHlywtYEjchtEUKMz9SZyD3TTa7WMz4vTOiEWvNquv7rJYlR0kg0zoblF6t6WWLlLit373QzfKSnv9NU6+WQHle08HQInNF4hWCX9+gVRE6koPKImLMwlcPQuzKllfLmEweWcTDlBV5qahzPZo+imTYobyLgq8YuwvR+8qdCz1UgC0Lwvt2xHD5c=
  run:
  - rake db:migrate
  - rake db:seed
  - restart
  - rake cleanup
