language: ruby
cache: bundler
rvm:
- 2.4.1
sudo: false
before_script:
- bundle exec rake db:migrate
- bundle exec rails s -d
script:
- bundle exec rake test
- bundle exec rubocop
deploy:
  provider: heroku
  api_key:
    secure: hsJgRJpH5suO9CCZlc7FXzYVPkc8pX0ikPa/vhDpQg0ge75zfS+NCkasa2rT6LrI3d/1bhz6Q5i19zVAU9HV5xaStl9Sf+j8GqQ7IKzTSb7VIQw4AUWkcJVl1/YgT1cMkDx1H4Js5QbCIH4o2gFjndvU2V75KlCmFFEsMVXK5hZ0GuBbgEVP2rEGJhVxXS3NX+yng67QwWC9g44N1mD4t7jtTi9DLsuJOaJ7y6hIVYtu772B/GSFYWueUSYLPxtBJxi+Z5jDjjx6eG77TSZMjca/mx1C6596o33muITMlcetyzK3xAQjUyViVWn+BjfHTkoj1/sz8+PKlNG5tVF3A6Hc1BZf6jSxqvIaDj95iV+LNGN7l/bTVIr1bmPJzUs9QCwv9BlyS8HGa250mwBaXa8bakTHQIerhOX7VmJqyUYTyUZGs1jN3BtVLFlu1SQ3MSgxBl6M3d7CPDufYsxNEw4PlCNmrmm2Se3aY4ctlT4GsDa0TkCBD56PSVv900cPWKP0oq4Tmu4IFZDGuJLA7/8drhUGXQI7Gt803PZPIGgNqOWcrzOEXBSxKGFq31zEcOpqXKSjqipAbKlYrh2h1F+8zQA5LmZaMvJzcqUVcpkt8TWPG5rYFLzm/klHtKDruUg9fDcBwUSvHHUnzJqP0SY59LtMgTymw5gB/ALvzeE=
  run:
  - rake db:migrate
  - rake db:seed
  - restart
  - rake cleanup
